# Cấu hình server
server.port=8080

# Cấu hình View Resolver cho JSP
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Cấu hình kết nối PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/kidsmath
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Tắt tự động chạy schema/data.sql (chạy thủ công hoặc đổi thành always khi cần)
spring.sql.init.mode=never
